#
# docker-comopose.yml
#  個人用のdocker-comoseファイルです。
#
# ・起動するときは docker-compose up -d で起動してください。
# 

version: "3"
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/tmp/working
    working_dir: /tmp/working
    ports:
      - 9999:9999
    command: jupyter lab --ip=0.0.0.0 --port=9999 --allow-root --no-browser